name: pack

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
      - name: Deploy to Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /build/libs/soms-1.0.0.jar
          remote: /data/deploy/soms-1.0.0.jar
          host: '139.9.157.89' # 你的公网地址
          username: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          password: DUT-SHM-1
      - name: start_eureka
        uses: appleboy/ssh-action@master
        with:
          host: '139.9.157.89' # 你的公网地址
          username: root
          password: DUT-SHM-1
          script: |
            ps -ef|grep soms-1.0.0.jar| grep -v grep|cut -c 9-15| xargs kill -s 9
            nohup java -jar /data/deploy/soms-1.0.0.jar >> /data/deploy/soms.log 2>&1 &